on:
  push:
    branches:
      - master

name: Deploy to Amazon S3

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: 12
      env:
        CI: true

    - name: Build App
      run: |
        cd frontend &&
        npm i &&
        npm run build

    - name: Test App
      run: |
        cd frontend &&
        npm run test

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy files to S3
      run: |
        # push to S3 and update index
        cd frontend
        aws s3 sync --acl public-read --cache-control 'max-age=604800' --delete --exclude index.html dist s3://vue-frontend-tester/
        aws s3 sync --acl public-read --cache-control 'no-cache' dist/index.html s3://vue-frontend-tester/