on:
  push:
    branches:
      - master

name: Deploy to Amazon S3

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Node.js app
      uses: actions/setup-node@v1
      with:
        node-version: 12
      env:
        SHA: ${{ github.sha }}
    - run: |
        # set public path env to this commit's SHA
        cd frontend &&
        printf "\nVUE_APP_PUBLIC_PATH=$SHA" >> .env.production &&
        npm i &&
        npm run build &&
        npm run test
      env:
        CI: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Deploy frontend files to static S3 server
      id: deploy-frontend
      env:
        SHA: ${{ github.sha }}
      run: |
        # place built frontend in directory with this commit's SHA
        mv frontend/dist frontend/$SHA
        # push to S3 and update index
        aws s3 sync --acl public-read frontend/$SHA s3://vue-frontend-tester/$SHA