name: API Tests

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Test ECS CLI version
      with:
        node-version: ${{ matrix.node-version }}
    - run: "echo ecs-cli --v"
      env:
        CI: true
