name: Web Tests

on:
  push:
    branches:
      - none
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install ecs-cli
        run: |
          mkdir -p "$HOME/tools/ecs-cli"
          wget -N -O "$HOME/tools/ecs-cli/ecs-cli" "https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-${VERSION-latest}"
          chmod +x "$HOME/tools/ecs-cli/ecs-cli"
          echo "::add-path::$HOME/tools/ecs-cli"

      - name: Test ecs-cli version
        run: ecs-cli --v
        env:
          CI: true
