name: Test

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Testing...
      - run: cd api && ecs-cli --v
        env:
          CI: true
